schema_version: 1

context:
  name: kaggle
  version: 2.2.4
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 28a58f6c1b9f46ce2afdfb439e0c4e91219e818b377ea4254f4e479456d8cb78

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - kaggle = kaggle.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - bleach
    - kagglesdk >=0.1.35,<1.0
    - python-slugify
    - requests
    - python-dateutil
    - tqdm
    - urllib3 >=1.15.1
    - packaging
    - protobuf
    - jupytext
    - python-dotenv
tests:
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check
      - if: unix
        then:
          - export KAGGLE_USERNAME=datadinosaur
          - export KAGGLE_KEY=xxxxxxxxxxxxxx
      - if: win
        then:
          - set KAGGLE_USERNAME=datadinosaur
          - set KAGGLE_KEY=xxxxxxxxxxxxxx
      - kaggle --help

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Kaggle API
  description: |
    Official API for https://www.kaggle.com, accessible using a command
    line tool implemented in Python.
  homepage: https://github.com/Kaggle/kaggle-api
  repository: https://github.com/Kaggle/kaggle-api
  documentation: https://github.com/Kaggle/kaggle-api

extra:
  recipe-maintainers:
    - ngam
    - CurtLH
    - synapticarbors
